### ISSUE TITLE
Perworldinv not working 1.14.2

### ISSUE THREAD

**Issue by ghost** [ZombieStriker/LobbyAPI#4]
Currently on 1.14.2 paper and perworldinventories isnt working anymore, it did work in 1.13.2 but not this update :(

**Comment by ZombieStriker** [comment]
What currently happens when you change worlds? Is it that inventories are cleared when a player goes to a world with the same savename, or that inventories are transferred across ones that do not?

Also, are there any errors in the console?

**Comment by ghost** [comment]
On world swap player has same items no matter the world. And no no errors in console. 
There is this sort of slight delay like 1-2 seconds where on world swap i would spawn with no items but the items would be transferred over as if they were being loaded from a file or something
**Little bit from the config to show that its actually enabled**
disallowHubCommandNoPerm: true
Settings:
  Enable_Per_World_Inventories: true
  worldselector:
    ==: org.bukkit.inventory.ItemStack

**Comment by ghost** [comment]
?

**Comment by ghost** [comment]
I fixed the problem. When i checked the config after readding all hub worlds they had a line for 
save: '~'  I changed the ~ to my world and now theyre saving seperately and problem solved.
