### ISSUE TITLE
(Bug) Broken link to update.

### ISSUE THREAD

**Issue by Ampernic** [ZombieStriker/LobbyAPI#6]
When the server starts, the plugin checks for updates, finds them, but cannot update.
The link to the updates in the plugin is indicated: "https://github.com/ZombieStriker/LobbyAPI/releases/download/v3.7.92/LobbyAPI", but it is not working, and the plan writes:
"(18: 01: 37 | WARN): java.io.FileNotFoundException: https://github.com/ZombieStriker/LobbyAPI/releases/download/v3.7.92/LobbyAPI
(18: 01: 37 | WARN): at sun.net.www.protocol.http.HttpURLConnection.getInputStream0 (HttpURLConnection.java:1890)
(18: 01: 37 | WARN): at sun.net.www.protocol.http.HttpURLConnection.access $ 200 (HttpURLConnection.java:91)
(18: 01: 37 | WARN): at sun.net.www.protocol.http.HttpURLConnection $ 9.run (HttpURLConnection.java:1484)
(18: 01: 37 | WARN): at sun.net.www.protocol.http.HttpURLConnection $ 9.run (HttpURLConnection.java:1482)
(18: 01: 37 | WARN): at java.security.AccessController.doPrivileged (Native Method)
(18: 01: 37 | WARN): at java.security.AccessController.doPrivilegedWithCombiner (AccessController.java:782)
(18: 01: 37 | WARN): at sun.net.www.protocol.http.HttpURLConnection.getInputStream (HttpURLConnection.java:1481)
(18: 01: 37 | WARN): at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream (HttpsURLConnectionImpl.java:263)
(18: 01: 37 | WARN): at java.net.URL.openStream (URL.java:1045)
(18: 01: 37 | WARN): at me.zombie_striker.lobbyapi.utils.GithubUpdater $ 1.run (GithubUpdater.java:57)
(18: 01: 37 | WARN): at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run (CraftTask.java:76)
(18: 01: 37 | WARN): at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run (CraftAsyncTask.java:52)
(18: 01: 37 | WARN): at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
(18: 01: 37 | WARN): at java.util.concurrent.ThreadPoolExecutor $ Worker.run (ThreadPoolExecutor.java:624)
(18: 01: 37 | WARN): at java.lang.Thread.run (Thread.java:748) "

**Comment by ZombieStriker** [comment]
This should be fixed in the new update.
