### ISSUE TITLE
NullPointerException: null

### ISSUE THREAD

**Issue by TheLonelyWolf1** [ZombieStriker/LobbyAPI#8]
Hello,

Recently, LobbyAPI gave an Error with it's newest version after somebody logged in. 

**Situation**: As soon as I logged in, I got spawned to the hub and couldn't move around or teleport anywhere. It startet today as I updated LobbyAPI from Version 3.7.98 to 3.7.99. 

The Problem was fixed, as soon as i downgraded back to 3.7.98.

**Some Info**:
**ServerSoftware:** Paper 1.14.4 Build200
**LobbyAPI-Config:** https://pastebin.com/xP8PasuN
**Relevant-Logs with the Error:** https://pastebin.com/YwJLbpmu 

If you need more information, then please ask me

Greetings,
TheLonelyWolf

**Comment by ZombieStriker** [comment]
This will be fixed in the next update.
